// Copyright (c) 2026 Barry Adams / CADcoLabs. All rights reserved.
//
// Walks a folder of DXF files (one subfolder per category, mirroring the
// SolidWorks export's structure) and converts each into a symbol-palette
// category module. Two entry points:
//   - generateCategories(dxfRootDir) -- pure-ish (does read the
//     filesystem, but no side effects beyond reading), used by the test
//     and by writeCategoriesModule below.
//   - writeCategoriesModule(dxfRootDir, outFile) -- generates and writes
//     js/symbols/data/mapiProfiles.js. Run directly: `node generate.mjs
//     <dxfRootDir> <outFile>`.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { dxfTextToSvg } from './dxf-to-svg.mjs';

function titleCase(folderName) {
  // Splits on whitespace/underscore only -- NOT hyphen, so a folder like
  // "round tube 6063-T5" keeps "6063-T5" as one word (matches the DXF
  // export's naming) instead of becoming "6063 T5".
  return folderName
    .split(/[\s_]+/)
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(' ');
}

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

/**
 * @param {string} dxfRootDir - one subfolder per category, .dxf files inside
 * @returns {{ categories: Array, failures: Array<{file: string, reason: string}> }}
 */
export function generateCategories(dxfRootDir) {
  const categories = [];
  const failures = [];
  const subfolders = fs.readdirSync(dxfRootDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  for (const folder of subfolders) {
    const folderPath = path.join(dxfRootDir, folder);
    const files = fs.readdirSync(folderPath)
      .filter((f) => f.toLowerCase().endsWith('.dxf'))
      .sort();

    const symbols = [];
    for (const file of files) {
      const filePath = path.join(folderPath, file);
      const baseName = file.slice(0, -4); // strip ".dxf"
      try {
        const text = fs.readFileSync(filePath, 'utf8');
        const result = dxfTextToSvg(text);
        if (!result) {
          failures.push({ file: filePath, reason: 'No supported entities' });
          continue;
        }
        symbols.push({
          id: `mapi-profile-${slugify(folder)}-${slugify(baseName)}`,
          name: baseName,
          svg: result.svg,
        });
      } catch (e) {
        failures.push({ file: filePath, reason: e.message });
      }
    }

    if (symbols.length > 0) {
      categories.push({
        id: `mapi-profile-${slugify(folder)}`,
        name: `MAPI — ${titleCase(folder)}`,
        industry: 'aec',
        country: 'us',
        color: '#0055a6', // MAPI brand blue, matches the app icon
        icon: `<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="2" y="2" width="12" height="12" rx="1"/><text x="8" y="11" font-size="7" font-weight="bold" fill="currentColor" stroke="none" text-anchor="middle" font-family="sans-serif">M</text></svg>`,
        builtin: true,
        symbols,
      });
    }
  }

  return { categories, failures };
}

export function writeCategoriesModule(dxfRootDir, outFile) {
  const { categories, failures } = generateCategories(dxfRootDir);
  const header = `// Copyright (c) 2026 Barry Adams / CADcoLabs. All rights reserved.\n` +
    `// Auto-generated by scripts/mapi-profiles/generate.mjs from the SolidWorks\n` +
    `// weldment profile export. Do not hand-edit -- re-run the generator instead.\n\n`;
  const body = `export const MAPI_PROFILE_CATEGORIES = ${JSON.stringify(categories, null, 2)};\n`;
  fs.writeFileSync(outFile, header + body);
  return { count: categories.reduce((n, c) => n + c.symbols.length, 0), failures };
}

// CLI entry point: `node generate.mjs <dxfRootDir> <outFile>`
if (fileURLToPath(import.meta.url) === path.resolve(process.argv[1] || '')) {
  const [, , dxfRootDir, outFile] = process.argv;
  if (!dxfRootDir || !outFile) {
    console.error('Usage: node generate.mjs <dxfRootDir> <outFile>');
    process.exit(1);
  }
  const { count, failures } = writeCategoriesModule(dxfRootDir, outFile);
  console.log(`Wrote ${count} symbols to ${outFile}.`);
  if (failures.length) {
    console.log(`${failures.length} file(s) failed to convert:`);
    for (const f of failures) console.log(`  ${f.file}: ${f.reason}`);
  }
}
